name: Cppcheck Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck  # Install Cppcheck on the runner

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --force --std=c99 main.c sensor.c utils.c  # Run cppcheck locally in GitHub Actions

    - name: Upload cppcheck report
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-report
        path: cppcheck_report.txt
