name: Cppcheck Analysis

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or adjust as necessary)
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck  # Install Cppcheck

    - name: Run Cppcheck
      run: |
        make lint  # Run the cppcheck command from the Makefile

    - name: Upload cppcheck report
      uses: actions/upload-artifact@v3  # Updated to version 3
      with:
        name: cppcheck-report
        path: cppcheck_report.txt
