name: CMake and GoogleTest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install build-essential

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run Static Analysis (Cppcheck)
        run: make lint  # This runs the 'lint' target from the Makefile

      - name: Set up GoogleTest
        run: |
          git submodule update --init --recursive

      - name: Build and Run Tests
        run: make test  # This runs the 'test' target from the Makefile
