name: Build and Test Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up GCC for compiling the project
      - name: Set up GCC
        run: sudo apt-get install build-essential gcc g++ make

      # Install GoogleTest (Optional: You can also install via package manager)
      - name: Install GoogleTest
        run: |
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp libgtest*.a /usr/lib

      # Install Cppcheck
      - name: Install Cppcheck
        run: sudo apt-get install cppcheck

      # Run Cppcheck for static analysis
      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --std=c99 src/ > cppcheck_report.txt

      # Run Unit Tests with GoogleTest
      - name: Build and run tests
        run: |
          make test

      # Upload Cppcheck report as artifact
      - name: Upload Cppcheck report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-report
          path: cppcheck_report.txt
