name: Cppcheck and GoogleTest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Cppcheck
      run: sudo apt install cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --force --quiet .

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev cmake

    - name: Build and run tests
      run: |
        make test  # Run your test using the Makefile without changing directories
