name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck git

      - name: Set up GoogleTest Submodule
        run: |
          git submodule update --init --recursive

      - name: Run Static Analysis (Cppcheck)
        run: |
          make lint  # This will call the 'lint' target from the Makefile

      - name: Run Unit Tests (GoogleTest)
        run: |
          make test  # This will call the 'test' target from the Makefile
