name: Cppcheck and GoogleTest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Make sure the submodule is checked out

    - name: Install Cppcheck
      run: sudo apt install cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --force --quiet .

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are initialized

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build GoogleTest
      run: make build_gtest  # Run the build_gtest rule in the Makefile

    - name: Build the project and run tests
      run: |
        make cppcheck    # Run cppcheck for static analysis
        make test        # Run GoogleTest tests
