name: C CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cppcheck cmake

    - name: Build Google Test
      run: |
        mkdir -p third_party/googletest/build
        cd third_party/googletest/build
        cmake ..
        make
        sudo cp lib/libgtest*.a /usr/lib/

    - name: Run Cppcheck
      run: make cppcheck

    - name: Build and Run Tests
      run: |
        make tests
        make test
